Feature/db challenge3
shimmer52/quelcode-db pull request #6
Opened 2020-12-08 21:04 UTC by shimmer52

データベース課題③
問題番号006~010
SQLの作成と実行

2020-12-10 13:04 UTC, choimake reviewed
拝見しました。
課題2お疲れ様です。

内容をみさせていただいた上で、ちょっと気になった点についてコメントさせてもらっています。確認の上対応お願いします。

2020-12-10 13:04 UTC, choimake commented on db/db-challenge3/db-006/db-006.sql
> +ORDER BY id
(修正不要)
`ASC`を記載した方が丁寧ではあります。

2020-12-10 13:04 UTC, choimake commented on db/db-challenge3/db-008/db-008.sql
> +FROM users u,chatrooms c,users_chatrooms j
いくつかのSQL文でFROM句で複数のテーブルを指定することでデータの結合を行っていますが、この方法だとデータの結合が「直積」になるので扱うデータ量が非常に多くなります。その結果、SELECTの実行速度が非常に遅くなるケースがあるので、普通のSELECT要件では推奨される書き方ではありません。

別の結合方法を使ってSQLを組み立ててみてください。

また「FROM句で複数のテーブルを指定する手法」について参考記事を以下においておきますので、時間があるときに確認してみてください。

参考
- http://blog.livedoor.jp/i_am_best/archives/6144729.html

2020-12-10 13:04 UTC, choimake commented on db/db-challenge3/db-010/db-010.sql
> +	AND u.is_deleted=0
ちょっとインデントが乱れているので直してほしいです。
可読性がもっとよくなります。

2020-12-11 05:02 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-12-11 05:02 UTC, piasoratech commented on db/db-challenge3/db-006/db-006.sql
> +ORDER BY id
SQLはどれもそうですが必ず`;`で終わるようにしてください
6～10まですべて修正をお願いします

2020-12-11 05:02 UTC, piasoratech commented on db/db-challenge3/db-006/db-006.sql
> +SELECT id,email,password,name,introduction,office_phone_number,cell_phone_number,is_deleted,created_at,updated_at
修正は不要ですが、可読性という意味で1点アドバイスをすると、`,`ごとに改行を入れることがおおいです。

SELECT id,
            email,
            password,
…
みたいな感じです。(上のはインデント揃えれてないですが、インデントも揃えます)

2020-12-11 05:02 UTC, piasoratech commented on db/db-challenge3/db-010/db-010.sql
> +GROUP BY tmp.chatroom_id)
この副問合せの部分はインデント一段下げるようにしましょう。

2020-12-11 05:02 UTC, piasoratech commented on db/db-challenge3/db-010/db-010.sql
> +AND u.is_deleted=0
削除されている投稿が含まれてしまっています。

2020-12-11 13:45 UTC, choimake approved these changes
対応ありがとうございました。
LGTMです。

2020-12-11 22:06 UTC, merged